### ISSUE TITLE
Gnome 44

### ISSUE THREAD

**Issue by jpjubenot** [raihan2000/circular-widgets#11]
Hi Raihan2000
You're extension is really cool.
Is there any opportunity to make it run over Gnome 44 ?
BR

**Comment by raihan2000** [comment]
@jpjubenot just add 44 in metadata.json it will work sorry for not updating on ego

**Comment by jpjubenot** [comment]
Thx a lot @raihan2000 .
It works perfectly, I am really fan of it.
