### ISSUE TITLE
Unable to reposition

### ISSUE THREAD

**Issue by no-name-99** [raihan2000/circular-widgets#2]
HI,

Unfortunately, I can not reposition the widget on my desktop. I have tried double click and dragging, left click, etc... it just does not work. Any suggestions, please?

**Comment by raihan2000** [comment]
@no-name-99 sorry for late replay, I think you have "Desktop Icons" extension enable on your system, try turning off "Desktop Icons" extension and move around using Cilck and Drag

**Comment by no-name-99** [comment]
Hi [@raihan2000,] yes . that seems to be the case. If Desktop Icons NG is on , the widget can not be repositioned : https://ibb.co/1zyTqXJ

**Comment by raihan2000** [comment]
@no-name-99 Yes desktop Icon extension interfares with this extensions drag n drop.
Let me see if I can find any permanent solution for this
