### ISSUE TITLE
Agenda language month names  + agenda widget keeps showing

### ISSUE THREAD

**Issue by ChristiaanWewer** [raihan2000/circular-widgets#3]
Hi,
The agenda widget keeps popping up even if turned off everytime I log in.
Also, the language of the month names is not in my system language (english). It names December as Dicember.
Cheers,
Chris

**Comment by raihan2000** [comment]
@ChristiaanWewer sorry, the month name is wrong for my silly typing mistake and I have noticed the widgets are by default enabled when you log out and log in or by disabling and then enabling, In next update it will be fixed and thanks for reporting the issue

**Comment by raihan2000** [comment]
@ChristiaanWewer [this commit](https://github.com/raihan2000/circular-widgets/commit/992aeb210aa106645800876abb283aa5051302f6) solved your issue in experimental branch

**Comment by madmangr** [comment]
@ChristiaanWewer Edit this file and rename Dicember to December and press Alt+F2 and enter the letter r and press enter key. 
 ~/.local/share/gnome-shell/extensions/circular@widgets.io/calendarWidgets.js

**Comment by k-kirill** [comment]
Is "Dicember" Italian + English mixture? :)

**Comment by raihan2000** [comment]
> Is "Dicember" Italian + English mixture? :)

Nope It's just my silly typing mistake
