### ISSUE TITLE
Add network usage and position

### ISSUE THREAD

**Issue by horga83** [raihan2000/circular-widgets#5]
Hello,
Nice extension, thank you.  Would be nice to have a network widget.
Also would it be easy to add a position parameter so it would be easy to line up the widgets?

**Comment by raihan2000** [comment]
thanx @horga83 can you explain about position parameter a little bit more??

**Comment by horga83** [comment]
Yes,

If you want to line up the widgets along say the right side of the
screen for example,  One could set a position of the widget so they are
all spaced evenly
and exactly.

For example with 3 widgets vertically down the side, they would all
have the same X coordinate but a different Y coordinate.

In an example screen of 1024x768 it would look like:

Widget 1   x=900, y=700
Widget 2   x=900, y=600
Widget 3   x=900, y=500

Cheers
Hope that helps.

**Comment by raihan2000** [comment]
I think it will be easy to click and drag those widgets on screen, btw I can set default position on screen then user can drag those widgets wherever they want on screen

**Comment by horga83** [comment]
Sure that is fine.  
BTW you can use imports.gi.GTop to get network stats, see the system monitor extension for reference. https://github.com/mgalgs/gnome-shell-system-monitor-applet

**Comment by raihan2000** [comment]
> Sure that is fine.  
> BTW you can use imports.gi.GTop to get network stats, see the system monitor extension for reference. https://github.com/mgalgs/gnome-shell-system-monitor-applet
> 

Sure I'm looking into it thanks for helping

**Comment by raihan2000** [comment]
![Screenshot from 2022-12-10 22-50-44](https://user-images.githubusercontent.com/46452545/206869439-80ff5a66-9285-420d-861b-aa528ca84512.png)

Net Speed meter on its way, already uploaded new version on [ego](https://extensions.gnome.org/extension/5530/circular-widgets/)

**Comment by horga83** [comment]
Many thanks for the network widget, just curious how hard it would be to smooth out the updates, maybe only show network usage after x number of bytes, so for example don't update on less than 10k B/s or something as such.  As it works right now it is a bit distracting as the rings update in a very "jerky" motion.

**Comment by raihan2000** [comment]
> Many thanks for the network widget, just curious how hard it would be to smooth out the updates, maybe only show network usage after x number of bytes, so for example don't update on less than 10k B/s or something as such. As it works right now it is a bit distracting as the rings update in a very "jerky" motion.

yeah I know I have not made any rules for updating  but if it has 1-1k bytes,1-1k megabytes it will update accordingly, just for example if there is 900 bytes then ring will be almost full with color after that if  there is 1 or 2 mb ring will be start from starting point
