### ISSUE TITLE
This throws a failed to open error.

### ISSUE THREAD

**Issue by horga83** [raihan2000/circular-widgets#7]
GLib.FileError: Failed to open file “/home/xxxx/.local/share/gnome-shell/extensions/circular@widgets.io/schemas/gschemas.compiled”: open() failed: No such file or directory

**Comment by raihan2000** [comment]
@horga83 did you build from repo ??

**Comment by raihan2000** [comment]
from terminal just do as it is 
```
cd ~/.local/share/gnome-shell/extensions/circular@widgets.io
glib-compile-schemas schemas/
```
then logout and login

**Comment by horga83** [comment]
No I just did an update when notified by the extensions app.

Cheers and thanks for the work on this.

**Comment by horga83** [comment]
Yes I did that and it is working. I guess that command is just missing
from the extension install script.

Thanks

**Comment by raihan2000** [comment]
Now updated version is fine thanks for reporting @horga83 

> No I just did an update when notified by the extensions app. Cheers and thanks for the work on this.
> […](#)
> On Sat, 2022-12-10 at 12:29 -0800, Raihan Ahamed wrote: @horga83 did you build from repo ?? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

you are wellcome @horga83
